import type { Row } from './harness';

const row = (tool: string, id: string, input: Record<string, unknown>, note: string): Row => ({ id: `${tool}.${id}`, tool, input, note });

/**
 * One row per class of input a retained mutating tool accepts today: each field, combinations,
 * and entity states (done, deferred, focused, missing). See docs/plans/mcp-parity-matrix.md.
 */
export const ROWS: Row[] = [
  // ── add_task ────────────────────────────────────────────────────────────────
  row('add_task', 'title-only', { title: 'New' }, 'Minimal call'),
  row('add_task', 'all-plain-fields', { title: 'New', notes: 'n', kickoff_note: 'k', task_type: 'plan' }, 'Notes, kickoff note and plan type'),
  row('add_task', 'project', { title: 'New', project_id: '$proj' }, 'Existing project'),
  row('add_task', 'project-missing', { title: 'New', project_id: '$noneProject' }, 'Project that does not exist'),
  row('add_task', 'bare-date', { title: 'New', due_date: '2026-11-01' }, 'Bare date is all-day at noon UTC'),
  row('add_task', 'datetime', { title: 'New', due_date: '2026-11-01T15:30:00Z' }, 'Timed due date'),
  row('add_task', 'offset-datetime', { title: 'New', due_date: '2026-11-01T10:30:00-05:00' }, 'Offset datetime is normalized to UTC'),
  row('add_task', 'date-and-recurrence', { title: 'New', due_date: '2026-11-01', recurrence: 'FREQ=WEEKLY' }, 'Recurring all-day task'),
  row('add_task', 'recurrence-without-date', { title: 'New', recurrence: 'FREQ=WEEKLY' }, 'Recurrence requires a due date'),
  row('add_task', 'recurrence-on-timed', { title: 'New', due_date: '2026-11-01T15:30:00Z', recurrence: 'FREQ=WEEKLY' }, 'Recurrence cannot sit on a timed due date'),
  row('add_task', 'bad-recurrence', { title: 'New', due_date: '2026-11-01', recurrence: 'FREQ=SECONDLY' }, 'Unsupported recurrence rule'),
  row('add_task', 'impossible-date', { title: 'New', due_date: '2026-02-30' }, 'Calendar date that does not exist'),
  row('add_task', 'bad-date', { title: 'New', due_date: 'next tuesday' }, 'Unparseable due date'),
  row('add_task', 'undeclared-due-all-day', { title: 'New', due_date: '2026-11-01T15:30:00Z', due_all_day: true }, 'due_all_day is not a declared argument and is ignored'),
  row('add_task', 'empty-title', { title: '' }, 'Empty title'),
  row('add_task', 'long-title', { title: 'x'.repeat(201) }, 'Title over 200 characters'),
  row('add_task', 'missing-title', {}, 'No title'),
  row('add_task', 'bad-type', { title: 'New', task_type: 'chore' }, 'Unknown task_type'),
  row('add_task', 'long-notes', { title: 'New', notes: 'x'.repeat(10_001) }, 'Notes over 10000 characters'),

  // ── complete_task ───────────────────────────────────────────────────────────
  row('complete_task', 'pending', { task_id: '$pend' }, 'Plain pending task'),
  row('complete_task', 'recurring', { task_id: '$weekly' }, 'Recurring task mints a successor and logs the recurrence'),
  row('complete_task', 'already-done', { task_id: '$done' }, 'Already done'),
  row('complete_task', 'deferred', { task_id: '$deferred' }, 'Deferred task'),
  row('complete_task', 'focused', { task_id: '$focused' }, 'Focused task loses its focus'),
  row('complete_task', 'blocked', { task_id: '$blocked' }, 'Task blocked by an open task'),
  row('complete_task', 'in-project', { task_id: '$member' }, 'Project member'),
  row('complete_task', 'missing', { task_id: '$none' }, 'Task does not exist'),

  // ── defer_task ──────────────────────────────────────────────────────────────
  row('defer_task', 'until', { task_id: '$pend', kind: 'until', until: '2026-12-01T09:00:00Z' }, 'Defer until a future instant'),
  row('defer_task', 'until-past', { task_id: '$pend', kind: 'until', until: '2020-01-01T00:00:00Z' }, 'Defer until an instant in the past'),
  row('defer_task', 'until-offset', { task_id: '$pend', kind: 'until', until: '2026-12-01T09:00:00+02:00' }, 'Offset instant is normalized'),
  row('defer_task', 'until-no-zone', { task_id: '$pend', kind: 'until', until: '2026-12-01T09:00:00' }, 'Timestamp without a zone'),
  row('defer_task', 'until-missing-value', { task_id: '$pend', kind: 'until' }, 'kind until without until'),
  row('defer_task', 'someday', { task_id: '$pend', kind: 'someday' }, 'Defer indefinitely'),
  row('defer_task', 'someday-with-until', { task_id: '$pend', kind: 'someday', until: '2026-12-01T09:00:00Z' }, 'someday rejects until'),
  row('defer_task', 'bad-kind', { task_id: '$pend', kind: 'later' }, 'Unknown kind'),
  row('defer_task', 'redefer', { task_id: '$deferred', kind: 'someday' }, 'Change an existing deferral'),
  row('defer_task', 'focused', { task_id: '$focused', kind: 'someday' }, 'Deferring a focused task'),
  row('defer_task', 'done', { task_id: '$done', kind: 'someday' }, 'Done task'),
  row('defer_task', 'missing', { task_id: '$none', kind: 'someday' }, 'Task does not exist'),

  // ── update_task ─────────────────────────────────────────────────────────────
  row('update_task', 'title', { task_id: '$notes', title: 'Renamed' }, 'Title only keeps notes and kickoff note'),
  row('update_task', 'notes', { task_id: '$notes', notes: 'new notes' }, 'Notes only keeps title and kickoff note'),
  row('update_task', 'notes-null', { task_id: '$notes', notes: null }, 'null clears notes'),
  row('update_task', 'kickoff-note', { task_id: '$notes', kickoff_note: 'new kickoff' }, 'Kickoff note only'),
  row('update_task', 'session-log', { task_id: '$notes', session_log: 'did things' }, 'Session log only'),
  row('update_task', 'task-type', { task_id: '$pend', task_type: 'plan' }, 'Task type only'),
  row('update_task', 'empty-title', { task_id: '$pend', title: '' }, 'Empty title'),
  row('update_task', 'due-only-keeps-recurrence', { task_id: '$weekly', due_date: '2026-10-12' }, 'New due date keeps recurrence'),
  row('update_task', 'recurrence-only-keeps-due', { task_id: '$weekly', recurrence: 'FREQ=MONTHLY' }, 'New recurrence keeps due date and all-day flag'),
  row('update_task', 'recurrence-only-no-due', { task_id: '$pend', recurrence: 'FREQ=WEEKLY' }, 'Recurrence on an undated task'),
  row('update_task', 'recurrence-onto-timed', { task_id: '$timed', recurrence: 'FREQ=WEEKLY' }, 'Recurrence on a timed due date'),
  row('update_task', 'due-timed-with-recurrence', { task_id: '$weekly', due_date: '2026-10-12T15:00:00Z' }, 'Timed due date on a recurring task'),
  row('update_task', 'due-null', { task_id: '$dueonly', due_date: null }, 'Clear the due date'),
  row('update_task', 'due-null-with-recurrence', { task_id: '$weekly', due_date: null }, 'Clear the due date but keep recurrence'),
  row('update_task', 'due-null-and-recurrence-null', { task_id: '$weekly', due_date: null, recurrence: null }, 'Clear both'),
  row('update_task', 'recurrence-null', { task_id: '$weekly', recurrence: null }, 'Clear recurrence, keep due date'),
  row('update_task', 'all-day-only', { task_id: '$timed', due_all_day: true }, 'Reclassify an existing due date'),
  row('update_task', 'all-day-only-no-due', { task_id: '$pend', due_all_day: true }, 'All-day flag on an undated task'),
  row('update_task', 'all-day-null', { task_id: '$dueonly', due_all_day: null }, 'Back to ambiguous'),
  row('update_task', 'due-with-all-day', { task_id: '$pend', due_date: '2026-11-01T15:00:00Z', due_all_day: true }, 'Explicit all-day beats the parsed classification'),
  row('update_task', 'bad-due', { task_id: '$pend', due_date: 'soon' }, 'Unparseable due date'),
  row('update_task', 'title-and-due', { task_id: '$notes', title: 'Both', due_date: '2026-11-01' }, 'Fields from two groups'),
  row('update_task', 'all-groups', { task_id: '$notes', title: 'All', task_type: 'plan', due_date: '2026-11-01', project_id: '$proj', session_log: 's' }, 'Several groups at once'),
  row('update_task', 'same-title', { task_id: '$notes', title: 'Has fields' }, 'A field set to the value it already has'),
  row('update_task', 'status-pending-on-pending', { task_id: '$pend', status: 'pending' }, 'No-op status on a pending task'),
  row('update_task', 'status-pending-with-title', { task_id: '$pend', status: 'pending', title: 'T' }, 'No-op status alongside a real field'),
  row('update_task', 'status-pending-on-done', { task_id: '$done', status: 'pending' }, 'Reopen via status'),
  row('update_task', 'status-pending-on-deferred', { task_id: '$deferred', status: 'pending' }, 'Status on a deferred task does not clear the deferral'),
  row('update_task', 'status-done', { task_id: '$pend', status: 'done' }, 'status done is refused'),
  row('update_task', 'status-bogus', { task_id: '$pend', status: 'archived' }, 'Unknown status value'),
  row('update_task', 'focus-set', { task_id: '$pend', focused_until: '2026-10-03T18:00:00Z' }, 'Focus until a future instant'),
  row('update_task', 'focus-set-on-deferred', { task_id: '$deferred', focused_until: '2026-10-03T18:00:00Z' }, 'Focusing a deferred task clears the deferral'),
  row('update_task', 'focus-set-on-done', { task_id: '$done', focused_until: '2026-10-03T18:00:00Z' }, 'Focus on a done task'),
  row('update_task', 'focus-clear', { task_id: '$focused', focused_until: null }, 'Clear focus'),
  row('update_task', 'focus-clear-unfocused', { task_id: '$pend', focused_until: null }, 'Clear focus that is not set'),
  row('update_task', 'focus-clear-on-done', { task_id: '$done', focused_until: null }, 'Clear focus on a done task'),
  row('update_task', 'focus-bad', { task_id: '$pend', focused_until: 'later' }, 'Unparseable focus instant'),
  row('update_task', 'project-move', { task_id: '$pend', project_id: '$proj' }, 'Move into a project'),
  row('update_task', 'project-remove', { task_id: '$member', project_id: null }, 'null removes the project'),
  row('update_task', 'project-missing', { task_id: '$pend', project_id: '$noneProject' }, 'Project that does not exist'),
  row('update_task', 'project-archived', { task_id: '$pend', project_id: '$archived' }, 'Archived project'),
  row('update_task', 'undeclared-defer', { task_id: '$pend', defer_kind: 'someday' }, 'defer_kind is not declared but passes straight through'),
  row('update_task', 'undeclared-defer-until', { task_id: '$pend', defer_kind: 'until', defer_until: '2026-12-01T09:00:00Z' }, 'Undeclared deferral pair'),
  row('update_task', 'undeclared-defer-none', { task_id: '$deferred', defer_kind: 'none', defer_until: null }, 'Undeclared clear of a deferral'),
  row('update_task', 'undeclared-unknown-key', { task_id: '$pend', colour: 'red' }, 'Unknown key'),
  row('update_task', 'empty-patch', { task_id: '$pend' }, 'Only task_id: nothing to change, still logs'),
  row('update_task', 'empty-patch-missing', { task_id: '$none' }, 'Empty patch on a missing task'),
  row('update_task', 'missing', { task_id: '$none', title: 'x' }, 'Task does not exist'),
  row('update_task', 'done-title', { task_id: '$done', title: 'Edited after done' }, 'Edit a done task'),
  row('update_task', 'done-due', { task_id: '$done', due_date: '2026-11-01' }, 'Schedule a done task'),

  // ── reopen_task ─────────────────────────────────────────────────────────────
  row('reopen_task', 'done', { task_id: '$done' }, 'Done task'),
  row('reopen_task', 'deferred', { task_id: '$deferred' }, 'Deferred task clears its deferral'),
  row('reopen_task', 'someday', { task_id: '$someday' }, 'Someday task'),
  row('reopen_task', 'pending', { task_id: '$pend' }, 'Plain pending task is refused'),
  row('reopen_task', 'missing', { task_id: '$none' }, 'Task does not exist'),

  // ── focus_task ──────────────────────────────────────────────────────────────
  row('focus_task', 'default-hours', { task_id: '$pend' }, 'Defaults to 3 hours'),
  row('focus_task', 'hours', { task_id: '$pend', hours: 1.5 }, 'Fractional hours'),
  row('focus_task', 'max-hours', { task_id: '$pend', hours: 24 }, 'Upper bound'),
  row('focus_task', 'null-hours', { task_id: '$pend', hours: null }, 'hours: null'),
  row('focus_task', 'negative-hours', { task_id: '$pend', hours: -1 }, 'Negative hours'),
  row('focus_task', 'zero-hours', { task_id: '$pend', hours: 0 }, 'Zero hours'),
  row('focus_task', 'too-many-hours', { task_id: '$pend', hours: 25 }, 'Over the bound'),
  row('focus_task', 'string-hours', { task_id: '$pend', hours: '2' }, 'Hours as a string'),
  row('focus_task', 'refocus', { task_id: '$focused', hours: 1 }, 'Replace an existing focus'),
  row('focus_task', 'deferred', { task_id: '$deferred' }, 'Focusing clears the deferral'),
  row('focus_task', 'done', { task_id: '$done' }, 'Done task'),
  row('focus_task', 'missing', { task_id: '$none' }, 'Task does not exist'),

  // ── delete_task ─────────────────────────────────────────────────────────────
  row('delete_task', 'plain', { task_id: '$pend' }, 'Plain task'),
  row('delete_task', 'with-links', { task_id: '$blocker' }, 'Link rows go with the task'),
  row('delete_task', 'in-project', { task_id: '$member' }, 'Project member'),
  row('delete_task', 'done', { task_id: '$done' }, 'Done task'),
  row('delete_task', 'missing', { task_id: '$none' }, 'Task does not exist'),

  // ── create_project ──────────────────────────────────────────────────────────
  row('create_project', 'title-only', { title: 'New project' }, 'Minimal call'),
  row('create_project', 'all-fields', { title: 'New project', notes: 'n', kickoff_note: 'k' }, 'Notes and kickoff note'),
  row('create_project', 'with-tasks', { title: 'New project', task_ids: ['$pend', '$pend2'] }, 'Assign existing tasks'),
  row('create_project', 'duplicate-task-ids', { title: 'New project', task_ids: ['$pend', '$pend'] }, 'Duplicate IDs count once'),
  row('create_project', 'moves-from-other-project', { title: 'New project', task_ids: ['$member'] }, 'Task already in another project'),
  row('create_project', 'missing-task', { title: 'New project', task_ids: ['$pend', '$none'] }, 'One task does not exist'),
  row('create_project', 'done-task', { title: 'New project', task_ids: ['$done'] }, 'Done task'),
  row('create_project', 'nineteen-tasks', { title: 'New project', task_ids: ['$bulk0', '$bulk1', '$bulk2', '$bulk3', '$bulk4', '$bulk5', '$bulk6', '$bulk7', '$bulk8', '$bulk9', '$bulk10', '$bulk11', '$bulk12', '$bulk13', '$bulk14', '$bulk15', '$bulk16', '$bulk17', '$bulk18'] }, '19 tasks'),
  row('create_project', 'twenty-tasks', { title: 'New project', task_ids: ['$bulk0', '$bulk1', '$bulk2', '$bulk3', '$bulk4', '$bulk5', '$bulk6', '$bulk7', '$bulk8', '$bulk9', '$bulk10', '$bulk11', '$bulk12', '$bulk13', '$bulk14', '$bulk15', '$bulk16', '$bulk17', '$bulk18', '$bulk19'] }, '20 tasks: more than the old 20-command bound allowed'),
  row('create_project', 'thirty-tasks', { title: 'New project', task_ids: ['$bulk0', '$bulk1', '$bulk2', '$bulk3', '$bulk4', '$bulk5', '$bulk6', '$bulk7', '$bulk8', '$bulk9', '$bulk10', '$bulk11', '$bulk12', '$bulk13', '$bulk14', '$bulk15', '$bulk16', '$bulk17', '$bulk18', '$bulk19', '$bulk20', '$bulk21', '$bulk22', '$bulk23', '$bulk24', '$bulk25', '$bulk26', '$bulk27', '$bulk28', '$bulk29'] }, '30 tasks'),
  row('create_project', 'forty-tasks', { title: 'New project', task_ids: ['$bulk0', '$bulk1', '$bulk2', '$bulk3', '$bulk4', '$bulk5', '$bulk6', '$bulk7', '$bulk8', '$bulk9', '$bulk10', '$bulk11', '$bulk12', '$bulk13', '$bulk14', '$bulk15', '$bulk16', '$bulk17', '$bulk18', '$bulk19', '$bulk20', '$bulk21', '$bulk22', '$bulk23', '$bulk24', '$bulk25', '$bulk26', '$bulk27', '$bulk28', '$bulk29', '$bulk30', '$bulk31', '$bulk32', '$bulk33', '$bulk34', '$bulk35', '$bulk36', '$bulk37', '$bulk38', '$bulk39'] }, '40 tasks'),
  row('create_project', 'empty-title', { title: '' }, 'Empty title'),
  row('create_project', 'non-array-task-ids', { title: 'New project', task_ids: 'x' }, 'task_ids is not an array'),

  // ── update_project ──────────────────────────────────────────────────────────
  row('update_project', 'title', { project_id: '$proj', title: 'Renamed' }, 'Title only keeps notes and kickoff note'),
  row('update_project', 'notes', { project_id: '$proj', notes: 'new' }, 'Notes only'),
  row('update_project', 'notes-null', { project_id: '$proj', notes: null }, 'null clears notes'),
  row('update_project', 'kickoff-note', { project_id: '$proj', kickoff_note: 'new' }, 'Kickoff note only'),
  row('update_project', 'archive', { project_id: '$proj', status: 'archived' }, 'Archive keeps members'),
  row('update_project', 'reopen', { project_id: '$archived', status: 'active' }, 'Reopen an archived project'),
  row('update_project', 'status-unchanged', { project_id: '$proj', status: 'active' }, 'Status already active'),
  row('update_project', 'archive-already-archived', { project_id: '$archived', status: 'archived' }, 'Status already archived'),
  row('update_project', 'title-and-status', { project_id: '$proj', title: 'Both', status: 'archived' }, 'Content and state together'),
  row('update_project', 'bad-status', { project_id: '$proj', status: 'paused' }, 'Unknown status'),
  row('update_project', 'empty-title', { project_id: '$proj', title: '' }, 'Empty title'),
  row('update_project', 'empty-patch', { project_id: '$proj' }, 'Only project_id: nothing to change, still logs'),
  row('update_project', 'empty-patch-missing', { project_id: '$noneProject' }, 'Empty patch on a missing project'),
  row('update_project', 'missing', { project_id: '$noneProject', title: 'x' }, 'Project does not exist'),

  // ── delete_project ──────────────────────────────────────────────────────────
  row('delete_project', 'with-members', { project_id: '$proj' }, 'Members are kept and detached'),
  row('delete_project', 'empty', { project_id: '$archived' }, 'Project without tasks'),
  row('delete_project', 'missing', { project_id: '$noneProject' }, 'Project does not exist'),

  // ── link_tasks ──────────────────────────────────────────────────────────────
  row('link_tasks', 'blocks-default', { from_task_id: '$pend', to_task_id: '$pend2' }, 'Default type is blocks'),
  row('link_tasks', 'blocks', { from_task_id: '$pend', to_task_id: '$pend2', link_type: 'blocks' }, 'Explicit blocks'),
  row('link_tasks', 'related', { from_task_id: '$pend2', to_task_id: '$pend', link_type: 'related' }, 'Related with descending IDs'),
  row('link_tasks', 'related-ascending', { from_task_id: '$pend', to_task_id: '$pend2', link_type: 'related' }, 'Related with the other orientation'),
  row('link_tasks', 'existing-blocks', { from_task_id: '$blocker', to_task_id: '$blocked' }, 'Link that already exists'),
  row('link_tasks', 'existing-related', { from_task_id: '$rel1', to_task_id: '$rel2', link_type: 'related' }, 'Related link that already exists'),
  row('link_tasks', 'existing-related-reversed', { from_task_id: '$rel2', to_task_id: '$rel1', link_type: 'related' }, 'Related link that exists in the other orientation'),
  row('link_tasks', 'reverse-blocks', { from_task_id: '$blocked', to_task_id: '$blocker' }, 'Would create a two-task cycle'),
  row('link_tasks', 'self', { from_task_id: '$pend', to_task_id: '$pend' }, 'Task to itself'),
  row('link_tasks', 'missing-from', { from_task_id: '$none', to_task_id: '$pend' }, 'Blocking task does not exist'),
  row('link_tasks', 'missing-to', { from_task_id: '$pend', to_task_id: '$none' }, 'Blocked task does not exist'),
  row('link_tasks', 'done-endpoint', { from_task_id: '$done', to_task_id: '$pend' }, 'Done task as an endpoint'),
  row('link_tasks', 'bad-type', { from_task_id: '$pend', to_task_id: '$pend2', link_type: 'duplicates' }, 'Unknown link type'),

  // ── unlink_tasks ────────────────────────────────────────────────────────────
  row('unlink_tasks', 'blocks-default', { from_task_id: '$blocker', to_task_id: '$blocked' }, 'Default type is blocks'),
  row('unlink_tasks', 'related', { from_task_id: '$rel1', to_task_id: '$rel2', link_type: 'related' }, 'Related link'),
  row('unlink_tasks', 'related-reversed', { from_task_id: '$rel2', to_task_id: '$rel1', link_type: 'related' }, 'Related link given in the other orientation'),
  row('unlink_tasks', 'absent', { from_task_id: '$pend', to_task_id: '$pend2' }, 'No such link'),
  row('unlink_tasks', 'wrong-type', { from_task_id: '$blocker', to_task_id: '$blocked', link_type: 'related' }, 'Link exists with another type'),
  row('unlink_tasks', 'wrong-orientation', { from_task_id: '$blocked', to_task_id: '$blocker' }, 'Blocks link in the other orientation'),
  row('unlink_tasks', 'missing-tasks', { from_task_id: '$none', to_task_id: '$none' }, 'Neither task exists'),
  row('unlink_tasks', 'bad-type', { from_task_id: '$pend', to_task_id: '$pend2', link_type: 'duplicates' }, 'Unknown link type'),

  // ── update_preference ───────────────────────────────────────────────────────
  row('update_preference', 'sort-by', { key: 'sort_by', value: 'due' }, 'Valid key and value; the row is new'),
  row('update_preference', 'overwrite-existing', { key: 'planning_prompt', value: 'auto' }, 'Replace a row the fixture already holds'),
  row('update_preference', 'same-value', { key: 'planning_prompt', value: 'never' }, 'Set a row to the value it already has'),
  row('update_preference', 'each-key-kickoff', { key: 'kickoff_nudge', value: 'never' }, 'Another key and value set'),
  row('update_preference', 'overwrite', { key: 'urgency_visibility', value: 'hide' }, 'A valid value on a key the fixture has not set'),
  row('update_preference', 'bad-value', { key: 'sort_by', value: 'colour' }, 'Value outside the key\'s set'),
  row('update_preference', 'bad-key', { key: 'favourite_food', value: 'x' }, 'Unknown key'),
  row('update_preference', 'internal-key', { key: 'last_session_at', value: '2026-10-01T00:00:00.000Z' }, 'Internal key'),
  row('update_preference', 'missing-value', { key: 'sort_by' }, 'No value'),
];
