import type { Row } from './harness';

const row = (tool: string, id: string, input: Record<string, unknown>, note: string): Row => ({ id: `${tool}.${id}`, tool, input, note });

/**
 * One row per class of input a retained mutating tool accepts today: each field, combinations,
 * and entity states (done, deferred, focused, missing). See docs/plans/mcp-parity-matrix.md.
 */
export const ROWS: Row[] = [
  // ── add_task ────────────────────────────────────────────────────────────────
  row('add_task', 'title-only', { title: 'New' }, 'Minimal call'),
  row('add_task', 'all-plain-fields', { title: 'New', notes: 'n', kickoff_note: 'k', task_type: 'plan' }, 'Notes, kickoff note and plan type'),
  row('add_task', 'project', { title: 'New', project_id: '$proj' }, 'Existing project'),
  row('add_task', 'project-missing', { title: 'New', project_id: '$noneProject' }, 'Project that does not exist'),
  row('add_task', 'bare-date', { title: 'New', due_date: '2026-11-01' }, 'Bare date is all-day at noon UTC'),
  row('add_task', 'datetime', { title: 'New', due_date: '2026-11-01T15:30:00Z' }, 'Timed due date'),
  row('add_task', 'offset-datetime', { title: 'New', due_date: '2026-11-01T10:30:00-05:00' }, 'Offset datetime is normalized to UTC'),
  row('add_task', 'date-and-recurrence', { title: 'New', due_date: '2026-11-01', recurrence: 'FREQ=WEEKLY' }, 'Recurring all-day task'),
  row('add_task', 'recurrence-without-date', { title: 'New', recurrence: 'FREQ=WEEKLY' }, 'Recurrence requires a due date'),
  row('add_task', 'recurrence-on-timed', { title: 'New', due_date: '2026-11-01T15:30:00Z', recurrence: 'FREQ=WEEKLY' }, 'Recurrence cannot sit on a timed due date'),
  row('add_task', 'bad-recurrence', { title: 'New', due_date: '2026-11-01', recurrence: 'FREQ=SECONDLY' }, 'Unsupported recurrence rule'),
  row('add_task', 'impossible-date', { title: 'New', due_date: '2026-02-30' }, 'Calendar date that does not exist'),
  row('add_task', 'bad-date', { title: 'New', due_date: 'next tuesday' }, 'Unparseable due date'),
  row('add_task', 'undeclared-due-all-day', { title: 'New', due_date: '2026-11-01T15:30:00Z', due_all_day: true }, 'due_all_day is not a declared argument and is ignored'),
  row('add_task', 'empty-title', { title: '' }, 'Empty title'),
  row('add_task', 'long-title', { title: 'x'.repeat(201) }, 'Title over 200 characters'),
  row('add_task', 'missing-title', {}, 'No title'),
  row('add_task', 'bad-type', { title: 'New', task_type: 'chore' }, 'Unknown task_type'),
  row('add_task', 'long-notes', { title: 'New', notes: 'x'.repeat(10_001) }, 'Notes over 10000 characters'),

  // ── complete_task ───────────────────────────────────────────────────────────
  row('complete_task', 'pending', { task_id: '$pend' }, 'Plain pending task'),
  row('complete_task', 'recurring', { task_id: '$weekly' }, 'Recurring task mints a successor and logs the recurrence'),
  row('complete_task', 'already-done', { task_id: '$done' }, 'Already done'),
  row('complete_task', 'deferred', { task_id: '$deferred' }, 'Deferred task'),
  row('complete_task', 'focused', { task_id: '$focused' }, 'Focused task loses its focus'),
  row('complete_task', 'blocked', { task_id: '$blocked' }, 'Task blocked by an open task'),
  row('complete_task', 'in-project', { task_id: '$member' }, 'Project member'),
  row('complete_task', 'missing', { task_id: '$none' }, 'Task does not exist'),

  // ── defer_task ──────────────────────────────────────────────────────────────
  row('defer_task', 'until', { task_id: '$pend', kind: 'until', until: '2026-12-01T09:00:00Z' }, 'Defer until a future instant'),
  row('defer_task', 'until-past', { task_id: '$pend', kind: 'until', until: '2020-01-01T00:00:00Z' }, 'Defer until an instant in the past'),
  row('defer_task', 'until-offset', { task_id: '$pend', kind: 'until', until: '2026-12-01T09:00:00+02:00' }, 'Offset instant is normalized'),
  row('defer_task', 'until-no-zone', { task_id: '$pend', kind: 'until', until: '2026-12-01T09:00:00' }, 'Timestamp without a zone'),
  row('defer_task', 'until-missing-value', { task_id: '$pend', kind: 'until' }, 'kind until without until'),
  row('defer_task', 'someday', { task_id: '$pend', kind: 'someday' }, 'Defer indefinitely'),
  row('defer_task', 'someday-with-until', { task_id: '$pend', kind: 'someday', until: '2026-12-01T09:00:00Z' }, 'someday rejects until'),
  row('defer_task', 'bad-kind', { task_id: '$pend', kind: 'later' }, 'Unknown kind'),
  row('defer_task', 'redefer', { task_id: '$deferred', kind: 'someday' }, 'Change an existing deferral'),
  row('defer_task', 'focused', { task_id: '$focused', kind: 'someday' }, 'Deferring a focused task'),
  row('defer_task', 'done', { task_id: '$done', kind: 'someday' }, 'Done task'),
  row('defer_task', 'missing', { task_id: '$none', kind: 'someday' }, 'Task does not exist'),

  // ── update_task ─────────────────────────────────────────────────────────────
  row('update_task', 'title', { task_id: '$notes', title: 'Renamed' }, 'Title only keeps notes and kickoff note'),
  row('update_task', 'notes', { task_id: '$notes', notes: 'new notes' }, 'Notes only keeps title and kickoff note'),
  row('update_task', 'notes-null', { task_id: '$notes', notes: null }, 'null clears notes'),
  row('update_task', 'kickoff-note', { task_id: '$notes', kickoff_note: 'new kickoff' }, 'Kickoff note only'),
  row('update_task', 'session-log', { task_id: '$notes', session_log: 'did things' }, 'Session log only'),
  row('update_task', 'task-type', { task_id: '$pend', task_type: 'plan' }, 'Task type only'),
  row('update_task', 'empty-title', { task_id: '$pend', title: '' }, 'Empty title'),
  row('update_task', 'due-only-keeps-recurrence', { task_id: '$weekly', due_date: '2026-10-12' }, 'New due date keeps recurrence'),
  row('update_task', 'recurrence-only-keeps-due', { task_id: '$weekly', recurrence: 'FREQ=MONTHLY' }, 'New recurrence keeps due date and all-day flag'),
  row('update_task', 'recurrence-only-no-due', { task_id: '$pend', recurrence: 'FREQ=WEEKLY' }, 'Recurrence on an undated task'),
  row('update_task', 'recurrence-onto-timed', { task_id: '$timed', recurrence: 'FREQ=WEEKLY' }, 'Recurrence on a timed due date'),
  row('update_task', 'due-timed-with-recurrence', { task_id: '$weekly', due_date: '2026-10-12T15:00:00Z' }, 'Timed due date on a recurring task'),
  row('update_task', 'due-null', { task_id: '$dueonly', due_date: null }, 'Clear the due date'),
  row('update_task', 'due-null-with-recurrence', { task_id: '$weekly', due_date: null }, 'Clear the due date but keep recurrence'),
  row('update_task', 'due-null-and-recurrence-null', { task_id: '$weekly', due_date: null, recurrence: null }, 'Clear both'),
  row('update_task', 'recurrence-null', { task_id: '$weekly', recurrence: null }, 'Clear recurrence, keep due date'),
  row('update_task', 'all-day-only', { task_id: '$timed', due_all_day: true }, 'Reclassify an existing due date'),
  row('update_task', 'all-day-only-no-due', { task_id: '$pend', due_all_day: true }, 'All-day flag on an undated task'),
  row('update_task', 'all-day-null', { task_id: '$dueonly', due_all_day: null }, 'Back to ambiguous'),
  row('update_task', 'due-with-all-day', { task_id: '$pend', due_date: '2026-11-01T15:00:00Z', due_all_day: true }, 'Explicit all-day beats the parsed classification'),
  row('update_task', 'bad-due', { task_id: '$pend', due_date: 'soon' }, 'Unparseable due date'),
  row('update_task', 'title-and-due', { task_id: '$notes', title: 'Both', due_date: '2026-11-01' }, 'Fields from two groups'),
  row('update_task', 'all-groups', { task_id: '$notes', title: 'All', task_type: 'plan', due_date: '2026-11-01', project_id: '$proj', session_log: 's' }, 'Several groups at once'),
  row('update_task', 'same-title', { task_id: '$notes', title: 'Has fields' }, 'A field set to the value it already has'),
  row('update_task', 'status-pending-on-pending', { task_id: '$pend', status: 'pending' }, 'No-op status on a pending task'),
  row('update_task', 'status-pending-with-title', { task_id: '$pend', status: 'pending', title: 'T' }, 'No-op status alongside a real field'),
  row('update_task', 'status-pending-on-done', { task_id: '$done', status: 'pending' }, 'Reopen via status'),
  row('update_task', 'status-pending-on-deferred', { task_id: '$deferred', status: 'pending' }, 'Status on a deferred task does not clear the deferral'),
  row('update_task', 'status-done', { task_id: '$pend', status: 'done' }, 'status done is refused'),
  row('update_task', 'status-bogus', { task_id: '$pend', status: 'archived' }, 'Unknown status value'),
  row('update_task', 'focus-set', { task_id: '$pend', focused_until: '2026-10-03T18:00:00Z' }, 'Focus until a future instant'),
  row('update_task', 'focus-set-on-deferred', { task_id: '$deferred', focused_until: '2026-10-03T18:00:00Z' }, 'Focusing a deferred task clears the deferral'),
  row('update_task', 'focus-set-on-done', { task_id: '$done', focused_until: '2026-10-03T18:00:00Z' }, 'Focus on a done task'),
  row('update_task', 'focus-clear', { task_id: '$focused', focused_until: null }, 'Clear focus'),
  row('update_task', 'focus-clear-unfocused', { task_id: '$pend', focused_until: null }, 'Clear focus that is not set'),
  row('update_task', 'focus-clear-on-done', { task_id: '$done', focused_until: null }, 'Clear focus on a done task'),
  row('update_task', 'focus-bad', { task_id: '$pend', focused_until: 'later' }, 'Unparseable focus instant'),
  row('update_task', 'project-move', { task_id: '$pend', project_id: '$proj' }, 'Move into a project'),
  row('update_task', 'project-remove', { task_id: '$member', project_id: null }, 'null removes the project'),
  row('update_task', 'project-missing', { task_id: '$pend', project_id: '$noneProject' }, 'Project that does not exist'),
  row('update_task', 'project-archived', { task_id: '$pend', project_id: '$archived' }, 'Archived project'),
  row('update_task', 'undeclared-defer', { task_id: '$pend', defer_kind: 'someday' }, 'defer_kind is not declared but passes straight through'),
  row('update_task', 'undeclared-defer-until', { task_id: '$pend', defer_kind: 'until', defer_until: '2026-12-01T09:00:00Z' }, 'Undeclared deferral pair'),
  row('update_task', 'undeclared-defer-none', { task_id: '$deferred', defer_kind: 'none', defer_until: null }, 'Undeclared clear of a deferral'),
  row('update_task', 'undeclared-unknown-key', { task_id: '$pend', colour: 'red' }, 'Unknown key'),
  row('update_task', 'empty-patch', { task_id: '$pend' }, 'Only task_id: nothing to change, still logs'),
  row('update_task', 'empty-patch-missing', { task_id: '$none' }, 'Empty patch on a missing task'),
  row('update_task', 'missing', { task_id: '$none', title: 'x' }, 'Task does not exist'),
  row('update_task', 'done-title', { task_id: '$done', title: 'Edited after done' }, 'Edit a done task'),
  row('update_task', 'done-due', { task_id: '$done', due_date: '2026-11-01' }, 'Schedule a done task'),

  // ── focus_task ──────────────────────────────────────────────────────────────
  row('focus_task', 'default-hours', { task_id: '$pend' }, 'Defaults to 3 hours'),
  row('focus_task', 'hours', { task_id: '$pend', hours: 1.5 }, 'Fractional hours'),
  row('focus_task', 'max-hours', { task_id: '$pend', hours: 24 }, 'Upper bound'),
  row('focus_task', 'null-hours', { task_id: '$pend', hours: null }, 'hours: null'),
  row('focus_task', 'negative-hours', { task_id: '$pend', hours: -1 }, 'Negative hours'),
  row('focus_task', 'zero-hours', { task_id: '$pend', hours: 0 }, 'Zero hours'),
  row('focus_task', 'too-many-hours', { task_id: '$pend', hours: 25 }, 'Over the bound'),
  row('focus_task', 'string-hours', { task_id: '$pend', hours: '2' }, 'Hours as a string'),
  row('focus_task', 'refocus', { task_id: '$focused', hours: 1 }, 'Replace an existing focus'),
  row('focus_task', 'deferred', { task_id: '$deferred' }, 'Focusing clears the deferral'),
  row('focus_task', 'done', { task_id: '$done' }, 'Done task'),
  row('focus_task', 'missing', { task_id: '$none' }, 'Task does not exist'),
];
