import { describe, expect, it } from 'vitest';
import { adoptLegacyTaskPlan } from '../src/domain/ops/duty';
import { applyPlan } from '../src/storage';
import { materializeDueDuties } from '../src/duties';
import { sqliteD1 } from './helpers/sqliteD1';

const at = (iso: string) => iso as never;
type Sql = ReturnType<typeof sqliteD1>['sql'];
function legacy(sql: Sql, id: string, over: Record<string, unknown> = {}) {
  const row = { id, title: 'Take out trash', notes: 'bins', status: 'pending', due_date: '2026-10-05T12:00:00Z', due_all_day: 1, recurrence: 'FREQ=WEEKLY;BYDAY=MO',
    created_at: '2026-09-01T00:00:00Z', updated_at: '2026-09-01T00:00:00Z', defer_kind: 'none', task_type: 'action', kickoff_note: 'Check the curb', ...over };
  const columns = Object.keys(row);
  sql.prepare(`INSERT INTO tasks(${columns.join(',')}) VALUES(${columns.map(() => '?').join(',')})`).run(...columns.map(column => (row as never)[column]));
}
const task = (sql: Sql, id: string) => sql.prepare('SELECT * FROM tasks WHERE id=?').get(id) as any;
const duties = (sql: Sql) => sql.prepare('SELECT * FROM duties ORDER BY id').all() as any[];

describe.each(['fresh', 'upgrade'] as const)('legacy recurrence adoption (%s)', mode => {
  it('binds an on-calendar task to a new duty as its current occurrence and clears the recurrence', async () => {
    const { sql, d1 } = sqliteD1(mode);
    try {
      legacy(sql, 't_trash');
      const summary = await materializeDueDuties(d1, at('2026-10-05T13:00:00Z'));
      expect(summary).toMatchObject({ adopted: 1, failed: 0 });
      expect(duties(sql)).toEqual([expect.objectContaining({ id: 'd_trash', rrule: 'FREQ=WEEKLY;BYDAY=MO', dtstart: '2026-10-05T12:00:00Z', timezone: null, status: 'active',
        last_spawned_at: '2026-10-05T12:00:00Z', next_occurrence_at: '2026-10-12T12:00:00Z', kickoff_note: 'Check the curb', catch_up: 'next' })]);
      expect(task(sql, 't_trash')).toMatchObject({ recurrence: null, duty_id: 'd_trash', occurrence_at: '2026-10-05T12:00:00Z', status: 'pending', title: 'Take out trash' });
      expect(sql.prepare('SELECT COUNT(*) AS n FROM tasks').get()).toEqual({ n: 1 });
      expect(await materializeDueDuties(d1, at('2026-10-05T13:00:00Z'))).toMatchObject({ adopted: 0 });
      // The next occurrence is generated by the calendar, all-day like the legacy successor was.
      await materializeDueDuties(d1, at('2026-10-12T13:00:00Z'));
      expect(sql.prepare("SELECT due_date,due_all_day FROM tasks WHERE duty_id='d_trash' AND id<>'t_trash'").get()).toEqual({ due_date: '2026-10-12T12:00:00Z', due_all_day: 1 });
    } finally { sql.close(); }
  });

  it('keeps an off-calendar task as a one-off and starts the series at its next occurrence', async () => {
    const { sql, d1 } = sqliteD1(mode);
    try {
      legacy(sql, 't_off001', { due_date: '2026-10-07T12:00:00Z' }); // a Wednesday for a Monday rule
      await materializeDueDuties(d1, at('2026-10-07T13:00:00Z'));
      expect(task(sql, 't_off001')).toMatchObject({ recurrence: null, duty_id: null, occurrence_at: null });
      expect(duties(sql)[0]).toMatchObject({ last_spawned_at: null, next_occurrence_at: '2026-10-12T12:00:00Z' });
    } finally { sql.close(); }
  });

  it('leaves records the engine cannot represent on the legacy completion path', async () => {
    const { sql, d1 } = sqliteD1(mode);
    try {
      legacy(sql, 't_count1', { recurrence: 'FREQ=DAILY;COUNT=3' });
      legacy(sql, 't_nodue1', { due_date: null, due_all_day: null });
      legacy(sql, 't_timed1', { due_all_day: 0 });
      legacy(sql, 't_done01', { status: 'done' });
      expect(await materializeDueDuties(d1, at('2026-10-05T13:00:00Z'))).toMatchObject({ adopted: 0, failed: 0 });
      expect(duties(sql)).toEqual([]);
      for (const id of ['t_count1', 't_timed1', 't_done01']) expect(task(sql, id).recurrence).not.toBeNull();
    } finally { sql.close(); }
  });

  it('reaches adoptable tasks behind a full page of unadoptable ones', async () => {
    const { sql, d1 } = sqliteD1(mode);
    try {
      for (let i = 0; i < 55; i += 1) legacy(sql, `t_a${String(i).padStart(4, '0')}`, { due_date: null, due_all_day: null });
      legacy(sql, 't_zlast');
      expect(await materializeDueDuties(d1, at('2026-10-05T13:00:00Z'))).toMatchObject({ adopted: 1, failed: 0 });
      expect(task(sql, 't_zlast').duty_id).toBe('d_zlast');
    } finally { sql.close(); }
  });

  it('does nothing when the task changed after the plan was made', async () => {
    const { sql, d1 } = sqliteD1(mode);
    try {
      legacy(sql, 't_race01');
      const plan = adoptLegacyTaskPlan(task(sql, 't_race01'), at('2026-10-05T13:00:00Z'));
      if (!plan.ok) throw new Error(plan.error);
      sql.prepare("UPDATE tasks SET status='done' WHERE id='t_race01'").run();
      expect((await applyPlan(d1, plan.value.plan)).ok).toBe(true);
      expect(duties(sql)).toEqual([]);
      expect(task(sql, 't_race01')).toMatchObject({ status: 'done', recurrence: 'FREQ=WEEKLY;BYDAY=MO', duty_id: null });
    } finally { sql.close(); }
  });
});
